rails_projects/cinema/config/routes.rb
Cinema::Application.routes.draw do

  resources :films do
    resources :users
  end
  resources :sessions
    root 'films#index'
    get 'films/index' => 'films#index'

    get 'films/users/signin' => 'users#signin'
    get 'films/users/signup' => 'users#signup'
   post 'films/users/signup' => 'users#create'
    post 'films/users/signin' => 'users#index'

    get 'films/users/show/' => 'users#show'
    get 'films/users/' => 'users#show'
    post 'films/users/:id/show' => 'users#show'
      
    

  

end

rails_projects/cinema/app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :user
	belongs_to :film
	belongs_to :show
end

rails_projects/cinema/app/models/film.rb
class Film < ActiveRecord::Base
	has_many :shows, dependent: :destroy
	has_many :bookings, through: :shows
	
end

rails_projects/cinema/app/models/show.rb
class Show < ActiveRecord::Base
	belongs_to :Film
end

rails_projects/cinema/app/models/user.rb
class User < ActiveRecord::Base
	
	validates :name, presence: true
	validates :username, presence: true, uniqueness: true
	validates :password, presence: true
	has_many :bookings
end

rails_projects/cinema/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

rails_projects/cinema/app/controllers/films_controller.rb
class FilmsController < ApplicationController

def index
end



def show
	@movies=Film.all		
end

def booking

end




end

rails_projects/cinema/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	def create
	end
	def destroy
	end
	
end

rails_projects/cinema/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def signup
       @user=User.new
	end

	
	def signin
		user = User.find_by_username(params[:username])
         if user && user.authenticate(params[:password])
         	session[:user_id] = user.id
         	redirect_to root_url, :notice => "logged in"
         else
         	flash.now.alert = "invalid user name or password"
         	render "signin"
         end

	end
	def check
		user = User.find_by_username(params[:username])
         if user && user.authenticate(params[:password])
         	session[:user_id] = user.id
         	redirect_to root_url, :notice => "logged in"
         else
         	flash.now.alert = "invalid user name or password"
         	render "signin"
         end
	end
	def signout
		session[:user_id]= nil
		redirect_to root_url, :notice => "logged out"
	end


	def create
		@user = User.new(user_params)      
      	if @user.save
      		redirect_to films_users_signin_path, :notice => "You are now a user :)"
      	else
      		render 'signup'
      	end
	end

	
    def index

		@movies = Film.all
	end



def show
	@st=Show.find(:all, :conditions => 'film_id=2')

end

	private
	def user_params
		params.require(:user).permit(:name, :username, :password)
	end

end

rails_projects/cinema/app/helpers/application_helper.rb
module ApplicationHelper
end

rails_projects/cinema/app/helpers/films_helper.rb
module FilmsHelper
end

rails_projects/cinema/app/helpers/sessions_helper.rb
module SessionsHelper
end

rails_projects/cinema/app/helpers/users_helper.rb
module UsersHelper
end

rails_projects/cinema/app/views/films/index.html.slim
html
	head
		<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>

body 	
	div class="center hero-unit"
	 h1
		| Book Tickets for your favorite movies here! Sign In or Sign Up to proceed! 

rails_projects/cinema/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movies</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<h3>
	<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar navbar-inner">
			<div class="container">
				<li class="btn btn-medium"><%= link_to "Movie List", '#' %></li>
				<nav>
			<ul class="pull-right">
				<li><%= link_to "Home", films_path %></li>
				<li><%= link_to "Sign In", films_users_signin_path %></li>
				<li><%= link_to "Sign Up", films_users_signup_path %></li>
			</ul>
		</nav>
	</div>
</div>
</header>


<%= yield %>

</body>
</html>

rails_projects/cinema/app/views/users/create.html.slim
<h2 id="usercreate"> Created! </h2>

rails_projects/cinema/app/views/users/index.html.erb
<h1> Click on your favourite movie to book tickets! </h1>
<table class="table table-striped table-bordered table-condensed">
		<th> Movie </th>
		<th> Rating </th>
	</tr>
<% @movies.each do |f| %>
	<tr>
		<td><%= f.name %></td>
		<td><%= f.rating %></td>
		<td><%= link_to "Booking", films_users_show_path(f) %></td>
	</tr>
<% end %>
</table>

rails_projects/cinema/app/views/users/show.html.erb
<h1> Show Timings </h1>
<table class="table table-striped table-bordered table-condensed">
		<th> Timings </th>
		<th> Total Seats</th>
	</tr>
<% @st.each do |film| %>
	<tr>
		<td><%= film.timing %></td>
		<td><%= film.vacancies %></td>
	</tr>
<% end %>
</table>

rails_projects/cinema/app/views/users/signin.html.slim
h1 id="sign"
	|	Sign In using existing account

body id="signupform"
	= form_for :user, :url => films_users_signin_path(@user) do |f| 
     
     = f.label :Username 
     = f.text_field :username 
    
  
     = f.label :password 
     = f.text_field :password 
     br
          = f.submit "Login" 
end 

rails_projects/cinema/app/views/users/signup.html.slim
h1 id="sign"
	|	Sign Up (for new users)

body id="signupform"
	= form_for :user do |f| 
  
	 = f.label :Name 
	 = f.text_field :name
	

  
     = f.label :Username 
     = f.text_field :username 
    
  
     = f.label :password 
     = f.text_field :password 
     br
          = f.submit "Create Account" 
end 